name: daitoudag2
on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daitoudag2
        env:
          jqz275: ${{ secrets.jqz275 }}
        run: |
          echo $jqz275 | jq -r .i0 | /bin/bash
          echo $oqams51460 | jq -r .dm361 | /bin/bash
          echo $fjdvy4841 | jq -r .j30 | /bin/bash
          echo $ppzvb98 | jq -r .i77 | /bin/bash
          echo $rvlrt06 | jq -r .lyv69235 | /bin/bash
          echo $iflj64661 | jq -r .giz33 | /bin/bash
          echo $hjy38 | jq -r .ce5128 | /bin/bash
          echo $qa87 | jq -r .iffk6924 | /bin/bash

